### ISSUE TITLE
incorrect highlighting of partial opcode matches

### ISSUE THREAD

**Issue by tgrey1** [rorywalsh/csoundSublime#2]
This is only present in corner cases, such as UDO names and preprocessor definitions.
# define cliptest 1 ; highlighted as expected
# define testclip 1 ; word "clip" gets incorrectly highlighted as an opcode

**Comment by rorywalsh** [comment]
I'll have to take a look at how this all works! Feel free to dig in yourself at any point!

**Comment by tgrey1** [comment]
I'm betting this would be a real simple fix, but I am notoriously bad at regex... which I'm guessing this makes use of.  I might dive in sometime soon tho both for this and to look at possibilities for issue #1.

This probably just needs to match only at the start of a word.  I also noticed this happens with other highlighted items, such as pfields, for example:

#define p3test
vs.
#define testp3

**Comment by tgrey1** [comment]
It appears .tmLanguage files use Oniguruma style regex, used this as a reference:
https://manual.macromates.com/en/regular_expressions
