### ISSUE TITLE
Microphone does not work

### ISSUE THREAD

**Issue by Maay** [rorywalsh/csoundSublime#8]
'gaSig in' does not request the built-in microphone. It does request it from QT. MacOS, Build 3126.

**Comment by rorywalsh** [comment]
I'm not sure I follow? What is this in reference to?

**Comment by Maay** [comment]
When I'm trying to build my csound patch using csoundSublime it work well
until I need to use microfone for the input sygnal. It does not request the
system microfone. Same patch in csoundqt on the same devise worcks well
with microfone.

ср, 8 Мар 2017 г., 23:06 Rory Walsh <notifications@github.com>:

**Comment by Maay** [comment]
By requesting I mean it does not use it. It doesn't crash either. Is it
possible to use microfone in csound when running your patch from sublime?

ср, 8 Мар 2017 г., 23:14 Anton Aksentyuk <aksimas@gmail.com>:

**Comment by rorywalsh** [comment]
What OS are you on? It should work fine. All the Csound Sublime package
does is call the system Csound in a background process.

**Comment by Maay** [comment]
macOS 10.12.3, Sublime Build 3126. I've just checked again - works fine in csoundQT, doesn't work form sublime.

**Comment by rorywalsh** [comment]
It's probably because you haven't the correct CsOptions set. Are you using
-iadc?

**Comment by Maay** [comment]
That helped, thank you! I've been using -odac

**Comment by rorywalsh** [comment]
No problem. Glad you got it sorted ;)
